{{- $fullName := include "deployment-templates.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ns := .Release.Namespace -}}
{{- $loadurl := printf "http://flagger-loadtester.%s/" $ns -}}
{{- $canary_acceptance_test_cmd := printf "curl -sd 'test' http://%s-canary.%s/ "  $fullName $ns -}}
{{- $canary_loadtest_cmd := printf "hey -z 1m -q 10 -c 2 http://%s/" (index .Values.ingress.hosts 0).host -}}
{{- $bluegreen_acceptance_test_cmd := printf "curl -sd 'test' http://%s-canary.%s/token | grep token"  $fullName $ns -}}
{{- $bluegreen_loadtest_cmd := printf "hey -z 1m -q 10 -c 2 http://%s-canary.%s/" $fullName $ns -}}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "deployment-templates.fullname" . }}
  labels:
    {{- include "deployment-templates.labels" . | nindent 4 }}
spec:
  provider: nginx
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "deployment-templates.fullname" . }}
  # ingress reference
  ingressRef:
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    name: {{ include "deployment-templates.fullname" . }}
  # HPA reference (optional)
  #autoscalerRef:
  #  apiVersion: autoscaling/v2beta1
  #  kind: HorizontalPodAutoscaler
  #  name: podinfo
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # ClusterIP port number
    port: 80
    # container port number or name
    targetPort: {{ $svcPort }}
{{- if eq .Values.update.mode "Canary" }}
  analysis:
    # schedule interval (default 60s)
    interval: 3s
    # max number of failed metric checks before rollback
    threshold: 60
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 2
    # NGINX Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 1m
    # testing (optional)
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: {{ $loadurl | quote}}
        timeout: 30s
        metadata:
          type: bash
          cmd: {{ $canary_acceptance_test_cmd | quote }}
      - name: load-test
        url: {{ $loadurl | quote }}
        timeout: 5s
        metadata:
          cmd: {{ $canary_loadtest_cmd | quote }}
{{- end }}
{{- if eq .Values.update.mode "BlueGreen" }}
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed checks before rollback
    threshold: 2
    # number of checks to run before rollback
    iterations: 5
    # Prometheus checks based on 
    # http_request_duration_seconds histogram
    metrics:
      - name: request-success-rate
        # minimum req success rate (non 5xx responses)
        # percentage (0-100)
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        # maximum req duration P99
        # milliseconds
        thresholdRange:
          max: 500
        interval: 30s
    # acceptance/load testing hooks
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: {{ $loadurl | quote}}
        timeout: 15s
        metadata:
          type: bash
          cmd: {{ $bluegreen_acceptance_test_cmd }}
      - name: load-test
        url: {{ $loadurl | quote}}
        timeout: 5s
        metadata:
          type: cmd
          cmd: {{ $bluegreen_loadtest_cmd }}
{{- end }}
