{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployment-templates.serviceAccountName" . }}
  labels:
{{ include "deployment-templates.labels" . | nindent 4 }}
{{- end -}}
